name: Build and Push

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - "main"
  # schedule:
  #   - cron: "0 0 1 * *" # every month

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v3
      - name: Pull, tag, push and create new manifest
        run: ./manylinux2014.sh


